export const countries = [
  { id: 'NG', name: 'Nigeria' },
  { id: 'GH', name: 'Ghana' },
  { id: 'KE', name: 'Kenya' },
  { id: 'ZA', name: 'South Africa' },
  { id: 'UK', name: 'United Kingdom' },
  { id: 'US', name: 'United States' },
];

export const states = {
  NG: [
    { id: 'AB', name: 'Abia' },
    { id: 'FC', name: 'Abuja Federal Capital Territory' },
    { id: 'AD', name: 'Adamawa' },
    { id: 'AK', name: 'Akwa Ibom' },
    { id: 'AN', name: 'Anambra' },
    { id: 'BA', name: 'Bauchi' },
    { id: 'BY', name: 'Bayelsa' },
    { id: 'BE', name: 'Benue' },
    { id: 'BO', name: 'Borno' },
    { id: 'CR', name: 'Cross River' },
    { id: 'DE', name: 'Delta' },
    { id: 'EB', name: 'Ebonyi' },
    { id: 'ED', name: 'Edo' },
    { id: 'EK', name: 'Ekiti' },
    { id: 'EN', name: 'Enugu' },
    { id: 'GO', name: 'Gombe' },
    { id: 'IM', name: 'Imo' },
    { id: 'JI', name: 'Jigawa' },
    { id: 'KD', name: 'Kaduna' },
    { id: 'KN', name: 'Kano' },
    { id: 'KT', name: 'Katsina' },
    { id: 'KE', name: 'Kebbi' },
    { id: 'KO', name: 'Kogi' },
    { id: 'KW', name: 'Kwara' },
    { id: 'LA', name: 'Lagos' },
    { id: 'NA', name: 'Nasarawa' },
    { id: 'NI', name: 'Niger' },
    { id: 'OG', name: 'Ogun' },
    { id: 'ON', name: 'Ondo' },
    { id: 'OS', name: 'Osun' },
    { id: 'OY', name: 'Oyo' },
    { id: 'PL', name: 'Plateau' },
    { id: 'RI', name: 'Rivers' },
    { id: 'SO', name: 'Sokoto' },
    { id: 'TA', name: 'Taraba' },
    { id: 'YO', name: 'Yobe' },
    { id: 'ZA', name: 'Zamfara' },
  ],
  GH: [
    { id: 'AH', name: 'Ashanti' },
    { id: 'BA', name: 'Brong-Ahafo' },
    { id: 'CP', name: 'Central' },
    { id: 'EP', name: 'Eastern' },
    { id: 'AA', name: 'Greater Accra' },
    { id: 'NP', name: 'Northern' },
    { id: 'UE', name: 'Upper East' },
    { id: 'UW', name: 'Upper West' },
    { id: 'VP', name: 'Volta' },
    { id: 'WP', name: 'Western' },
  ],
  KE: [
    { id: 'CE', name: 'Central' },
    { id: 'CO', name: 'Coast' },
    { id: 'EA', name: 'Eastern' },
    { id: 'NA', name: 'Nairobi' },
    { id: 'NO', name: 'North Eastern' },
    { id: 'NY', name: 'Nyanza' },
    { id: 'RI', name: 'Rift Valley' },
    { id: 'WE', name: 'Western' },
  ],
  ZA: [
    { id: 'EC', name: 'Eastern Cape' },
    { id: 'FS', name: 'Free State' },
    { id: 'GP', name: 'Gauteng' },
    { id: 'KZN', name: 'KwaZulu-Natal' },
    { id: 'LP', name: 'Limpopo' },
    { id: 'MP', name: 'Mpumalanga' },
    { id: 'NC', name: 'Northern Cape' },
    { id: 'NW', name: 'North West' },
    { id: 'WC', name: 'Western Cape' },
  ],
  UK: [
    { id: 'ENG', name: 'England' },
    { id: 'SCT', name: 'Scotland' },
    { id: 'WLS', name: 'Wales' },
    { id: 'NIR', name: 'Northern Ireland' },
  ],
  US: [
    { id: 'AL', name: 'Alabama' },
    { id: 'AK', name: 'Alaska' },
    { id: 'AZ', name: 'Arizona' },
    { id: 'AR', name: 'Arkansas' },
    { id: 'CA', name: 'California' },
    { id: 'CO', name: 'Colorado' },
    { id: 'CT', name: 'Connecticut' },
    { id: 'DE', name: 'Delaware' },
    { id: 'FL', name: 'Florida' },
    { id: 'GA', name: 'Georgia' },
    { id: 'HI', name: 'Hawaii' },
    { id: 'ID', name: 'Idaho' },
    { id: 'IL', name: 'Illinois' },
    { id: 'IN', name: 'Indiana' },
    { id: 'IA', name: 'Iowa' },
    { id: 'KS', name: 'Kansas' },
    { id: 'KY', name: 'Kentucky' },
    { id: 'LA', name: 'Louisiana' },
    { id: 'ME', name: 'Maine' },
    { id: 'MD', name: 'Maryland' },
    { id: 'MA', name: 'Massachusetts' },
    { id: 'MI', name: 'Michigan' },
    { id: 'MN', name: 'Minnesota' },
    { id: 'MS', name: 'Mississippi' },
    { id: 'MO', name: 'Missouri' },
    { id: 'MT', name: 'Montana' },
    { id: 'NE', name: 'Nebraska' },
    { id: 'NV', name: 'Nevada' },
    { id: 'NH', name: 'New Hampshire' },
    { id: 'NJ', name: 'New Jersey' },
    { id: 'NM', name: 'New Mexico' },
    { id: 'NY', name: 'New York' },
    { id: 'NC', name: 'North Carolina' },
    { id: 'ND', name: 'North Dakota' },
    { id: 'OH', name: 'Ohio' },
    { id: 'OK', name: 'Oklahoma' },
    { id: 'OR', name: 'Oregon' },
    { id: 'PA', name: 'Pennsylvania' },
    { id: 'RI', name: 'Rhode Island' },
    { id: 'SC', name: 'South Carolina' },
    { id: 'SD', name: 'South Dakota' },
    { id: 'TN', name: 'Tennessee' },
    { id: 'TX', name: 'Texas' },
    { id: 'UT', name: 'Utah' },
    { id: 'VT', name: 'Vermont' },
    { id: 'VA', name: 'Virginia' },
    { id: 'WA', name: 'Washington' },
    { id: 'WV', name: 'West Virginia' },
    { id: 'WI', name: 'Wisconsin' },
    { id: 'WY', name: 'Wyoming' },
  ],
};